### ISSUE TITLE
[doc] Issue in "Telco features (DPDK, SR-IOV, CPU isolation, huge pages, NUMA, etc.)" - typo

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#349] opened 2024-08-21 07:03 UTC
Telco features (DPDK, SR-IOV, CPU isolation, huge pages, NUMA, etc.):

https://documentation.suse.com/suse-edge/3.0/html/edge/atip-automated-provisioning.html#add-telco

"The **directed** network provisioning"
-> 
"The **direct** network provisioning "

**Comment by hardys** [comment] 2024-08-23 08:52
This is a duplicate of https://github.com/suse-edge/suse-edge.github.io/issues/350 - it's not a typo, the intention is to align with the "directed network provisioning" term ref https://github.com/suse-edge/suse-edge.github.io/pull/354

**Closed** 2024-08-23 13:04 UTC
