### ISSUE TITLE
[doc] Issue in "KubeVirt Dashboard Extension"

### ISSUE THREAD

**Issue by peteingithub** [suse-edge/suse-edge.github.io#329] opened 2024-07-18 08:13 UTC
KubeVirt Dashboard Extension:

https://documentation.suse.com/suse-edge/3.0/html/edge/components-rancher-dashboard-extensions.html#id-kubevirt-dashboard-extension

Link address incorrect

**Comment by ranjinimn** [comment] 2024-08-23 11:13
duplicate of https://github.com/suse-edge/suse-edge.github.io/issues/339

**Closed by ranjinimn** 2024-08-23 11:13 UTC
